### ISSUE TITLE
DeterministicPlannerAgent checkpoint saving error

### ISSUE THREAD

**Issue by songanz** [eleurent/rl-agents#24]
I have tried the DeterministicPlannerAgent in the Highway Env. During training, in the terminal, it published that a checkpoint model is saved. However, I didn't find the saved checkpoint policy at claiming location

**Comment by eleurent** [comment]
Thanks for pointing that out, I agree that this message is misleading.
It is normal that you cannot find a saved checkpoint since DeterministicPlannerAgent is only a tree-search algorithm with no learnable part, so there is indeed nothing to save.
The message actually means that we *tried* to save the agent model and no error occured, but here nothing actually happened. 
I'll fix it so that we only get this message under actual and successful save (thus not for this agent)
