### ISSUE TITLE
Questions about MCTS

### ISSUE THREAD

**Issue by marooncn** [eleurent/rl-agents#47]
Hi, in _update_branch_ function, you update the parent node value with the same _total_reward_ with the current node. Why? I think they have different values, because action from parent node to current node will get a reward which should be added in parent _total_reward_.
```
    def update_branch(self, total_reward):
        self.update(total_reward)
        if self.parent:
            self.parent.update_branch(total_reward)
```

**Comment by marooncn** [comment]
And another question:
what's the function of _step_planner_ in _mcts.py_?

**Comment by eleurent** [comment]
> Hi, in update_branch function, you update the parent node value with the same total_reward with the current node. 
> Why? I think they have different values, because action from parent node to current node will get a reward which should be added in parent total_reward.

In fact, `total_reward` already contains the reward obtained at the parent step.
The estimated value of a node is the average of cumulative rewards from all trajectories that passed through this node.
You can think of it as composed of both:
- the future rewards when starting from this state (i.e. the usual definition of value V(s) in reinforcement learning)
- the past rewards obtained in the way to get to this state

Thus, when a trajectory is done, you should update the values of all nodes traversed with the same total reward.

In the end, following the UCB at a node with respect to past+future rewards should be similar to an UCB with only future rewards as you suggest (since all children of a node share the same past, so it has the same contribution to their values).

(Idk if that was clear...)

**Comment by eleurent** [comment]
And another question:
what's the function of step_planner in mcts.py?

When planning with MCTS, you simulate a bunch of trajectories, get an action recommendation, and run it on the true environment. Then, you need to start all over again for the next action. This `step_planner` function is intended to update the search tree (typically by getting the subtree rooted at the recommended action) when a planning phase is finished, in order to warm-start the planning phase at the next state.

**Comment by marooncn** [comment]
Thanks for your detailed reply, _step_planner_ seems unused, Why?

**Comment by eleurent** [comment]
Indeed, that’s a mistake. 
The code has been refactored, it should now be in the step() method of the planner (see AbstractPlanner.step())
Thank you for pointing it out, I will fix it soon.

**Comment by marooncn** [comment]
Is there any parallelization implementation for mcts, if I want to implement it, any advice?

**Comment by eleurent** [comment]
> Is there any parallelization implementation for mcts

There probably is, but not on this repository.

> if I want to implement it, any advice?

Depending on which tree-based planning algorithm you are considering, several parts could be parallelized.  Optimistic planners often consist in selecting the most promising sequence of actions, under current uncertainty. You could instead select the top-k sequences and run them in parallel, before updating the tree. There is probably some literature on the subject, but I haven't investigated it myself yet.
You will probably need to start several threads/processes with copies of the environment state (so that different trajectories can be sampled from that space), so you will probably have to ensure that the said environment object can be saved/loaded, e.g. with pickle.

**Comment by marooncn** [comment]
Thanks, I'll have a try.

**Comment by sritee** [comment]
> > Hi, in update_branch function, you update the parent node value with the same total_reward with the current node.
> > Why? I think they have different values, because action from parent node to current node will get a reward which should be added in parent total_reward.
> 
> In fact, `total_reward` already contains the reward obtained at the parent step.
> The estimated value of a node is the average of cumulative rewards from all trajectories that passed through this node.
> You can think of it as composed of both:
> 
> * the future rewards when starting from this state (i.e. the usual definition of value V(s) in reinforcement learning)
> * the past rewards obtained in the way to get to this state
> 
> Thus, when a trajectory is done, you should update the values of all nodes traversed with the same total reward.
> 
> In the end, following the UCB at a node with respect to past+future rewards should be similar to an UCB with only future rewards as you suggest (since all children of a node share the same past, so it has the same contribution to their values).
> 
> (Idk if that was clear...)

Thanks for the nice implementation. Curious why does the value update for a node include returns obtained before that node was visited? Ideally it only includes from that node onwards to end like traditional RL setting. Otherwise it looks like it is rewarded for something which happened in the past, and this could be an issue in a dense reward and receding horizon setting.

**Comment by eleurent** [comment]
I think the two formulations are equivalent (ie when choosing the next action to take, comparing `past + future1` with `past + future 2` is the same as just comparing `future1` with `future2`.
But I agree that your proposal is more intuitive, maybe I should change it. I don't really remember why I implemented it this way in the first place :thinking:

**Comment by sritee** [comment]
thanks, another question I had was in https://github.com/eleurent/rl-agents/blob/cf9c85aeede1bb1877b5be2940ec9262b66fc64b/rl_agents/agents/tree_search/mcts.py#L301, should the weight for the first term be 1 - regularization?

**Comment by sritee** [comment]
> I think the two formulations are equivalent (ie when choosing the next action to take, comparing `past + future1` with `past + future 2` is the same as just comparing `future1` with `future2`.
> But I agree that your proposal is more intuitive, maybe I should change it. I don't really remember why I implemented it this way in the first place

That makes sense, I suppose the shift invariance of the UCB makes it so that the magnitude of the value function doesn't quite matter, but I suppose for other non-argmax or other policies it might make a difference.

**Comment by eleurent** [comment]
>  should the weight for the first term be 1 - regularization?

Yes it should! thank you for catching this, I'll fix it.

> but I suppose for other non-argmax or other policies it might make a difference

Indeed, it would matter for a Boltzmann policy for instance. In which case, it is probably best to ignore the past.
